In [38]:
# Import libraries
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Create a dataset

value_y_list = [78.5, 74.3, 104.3, 87.6, 95.9, 109.2, 102.7, 72.5, 93.1, 115.9, 83.8, 113.3, 109.4] # valores de Y
value_x1_list = [7, 1, 11, 11, 7, 11, 3, 1, 2, 21, 1, 11, 10] # valores de X1
value_x2_list = [26, 29, 56, 31, 52, 55, 71, 31, 54, 47, 40, 66, 68] # valores de X2
value_x3_list = [6, 15, 8, 8, 6, 9, 17, 22, 18, 4, 23, 9, 8] # valores de X3
value_x4_list = [60, 52, 20, 47, 33, 22, 6, 44, 22, 26, 34, 12, 12] # valores de X4

data_dict = {"Y":value_y_list,
             "X1":value_x1_list,
             "X2":value_x2_list,
             "X3":value_x3_list,
             "X4":value_x4_list}

print(data_dict)

# Turn a dictionary into a dataframe
df = pd.DataFrame(data_dict)

#print(df) Tabla básica

{'Y': [78.5, 74.3, 104.3, 87.6, 95.9, 109.2, 102.7, 72.5, 93.1, 115.9, 83.8, 113.3, 109.4], 'X1': [7, 1, 11, 11, 7, 11, 3, 1, 2, 21, 1, 11, 10], 'X2': [26, 29, 56, 31, 52, 55, 71, 31, 54, 47, 40, 66, 68], 'X3': [6, 15, 8, 8, 6, 9, 17, 22, 18, 4, 23, 9, 8], 'X4': [60, 52, 20, 47, 33, 22, 6, 44, 22, 26, 34, 12, 12]}


In [39]:
import numpy as np

# Convert the DataFrame to a NumPy array (matrix)
matrix_df = df.values

# Create a column of ones with the same number of rows as the matrix
ones_column = np.ones((matrix_df.shape[0], 1))

# Replace the first column of the matrix with ones
# We take all rows, the first column of ones, and then all columns from the second column of the original matrix onwards.
matrix_with_ones = np.concatenate((ones_column, matrix_df[:, 1:]), axis=1)

print("Original DataFrame as matrix:")
print(matrix_df)
print("\nMatrix with first column replaced by ones:")
print(matrix_with_ones)

Original DataFrame as matrix:
[[ 78.5   7.   26.    6.   60. ]
 [ 74.3   1.   29.   15.   52. ]
 [104.3  11.   56.    8.   20. ]
 [ 87.6  11.   31.    8.   47. ]
 [ 95.9   7.   52.    6.   33. ]
 [109.2  11.   55.    9.   22. ]
 [102.7   3.   71.   17.    6. ]
 [ 72.5   1.   31.   22.   44. ]
 [ 93.1   2.   54.   18.   22. ]
 [115.9  21.   47.    4.   26. ]
 [ 83.8   1.   40.   23.   34. ]
 [113.3  11.   66.    9.   12. ]
 [109.4  10.   68.    8.   12. ]]

Matrix with first column replaced by ones:
[[ 1.  7. 26.  6. 60.]
 [ 1.  1. 29. 15. 52.]
 [ 1. 11. 56.  8. 20.]
 [ 1. 11. 31.  8. 47.]
 [ 1.  7. 52.  6. 33.]
 [ 1. 11. 55.  9. 22.]
 [ 1.  3. 71. 17.  6.]
 [ 1.  1. 31. 22. 44.]
 [ 1.  2. 54. 18. 22.]
 [ 1. 21. 47.  4. 26.]
 [ 1.  1. 40. 23. 34.]
 [ 1. 11. 66.  9. 12.]
 [ 1. 10. 68.  8. 12.]]


In [40]:
# Calculate the transpose of the matrix_with_ones
transposed_matrix = matrix_with_ones.T

# Display the transposed matrix
print("Transposed matrix:")
print(transposed_matrix)

Transposed matrix:
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 7.  1. 11. 11.  7. 11.  3.  1.  2. 21.  1. 11. 10.]
 [26. 29. 56. 31. 52. 55. 71. 31. 54. 47. 40. 66. 68.]
 [ 6. 15.  8.  8.  6.  9. 17. 22. 18.  4. 23.  9.  8.]
 [60. 52. 20. 47. 33. 22.  6. 44. 22. 26. 34. 12. 12.]]


In [41]:
# Extract the 'Y' column as a NumPy array
y_array = df['Y'].values

# Reshape it into a column vector
y_vector = y_array.reshape(-1, 1)

print("Column vector Y:")
print(y_vector)

Column vector Y:
[[ 78.5]
 [ 74.3]
 [104.3]
 [ 87.6]
 [ 95.9]
 [109.2]
 [102.7]
 [ 72.5]
 [ 93.1]
 [115.9]
 [ 83.8]
 [113.3]
 [109.4]]


In [42]:
# Perform matrix multiplication: transposed_matrix * matrix_with_ones
product_matrix = np.dot(transposed_matrix, matrix_with_ones)

print("Product of transposed_matrix and matrix_with_ones:")
print(product_matrix)

Product of transposed_matrix and matrix_with_ones:
[[1.3000e+01 9.7000e+01 6.2600e+02 1.5300e+02 3.9000e+02]
 [9.7000e+01 1.1390e+03 4.9220e+03 7.6900e+02 2.6200e+03]
 [6.2600e+02 4.9220e+03 3.3050e+04 7.2010e+03 1.5739e+04]
 [1.5300e+02 7.6900e+02 7.2010e+03 2.2930e+03 4.6280e+03]
 [3.9000e+02 2.6200e+03 1.5739e+04 4.6280e+03 1.5062e+04]]


In [43]:
# Calculate the inverse of the product_matrix
inverse_product_matrix = np.linalg.inv(product_matrix)

print("Inverse of the product_matrix:")
print(inverse_product_matrix)

Inverse of the product_matrix:
[[ 8.20654575e+02 -8.44180186e+00 -8.45777985e+00 -8.63453878e+00
  -8.28974378e+00]
 [-8.44180186e+00  9.27104019e-02  8.56862094e-02  9.26373566e-02
   8.44549553e-02]
 [-8.45777985e+00  8.56862094e-02  8.75602572e-02  8.78666397e-02
   8.55980995e-02]
 [-8.63453878e+00  9.26373566e-02  8.78666397e-02  9.52014097e-02
   8.63919188e-02]
 [-8.28974378e+00  8.44549553e-02  8.55980995e-02  8.63919188e-02
   8.40311912e-02]]


In [44]:
import numpy as np

# Perform the multiplication: (X'X)^-1 * X'
intermediate_product = np.dot(inverse_product_matrix, transposed_matrix)

# Perform the final multiplication: ((X'X)^-1 * X') * Y
beta_coefficients = np.dot(intermediate_product, y_vector)

print("Regression Coefficients (Beta):")
print(beta_coefficients)

Regression Coefficients (Beta):
[[62.4053693 ]
 [ 1.55110265]
 [ 0.51016758]
 [ 0.1019094 ]
 [-0.14406103]]


In [45]:
B0=beta_coefficients[0]
B1=beta_coefficients[1]
B2=beta_coefficients[2]
B3=beta_coefficients[3]
B4=beta_coefficients[4]

In [46]:
df['Ypred'] = B0 + B1*df['X1'] + B2*df['X2'] + B3*df['X3'] + B4*df['X4']
df['Y-Ypred'] = df['Y'] - df['Ypred']
df['error'] = df['Y-Ypred']**2
df

,Y,X1,X2,X3,X4,Ypred,Y-Ypred,error
0,78.5,7,26,6,60,78.495240,0.004760,0.000023
1,74.3,1,29,15,52,72.788799,1.511201,2.283728
2,104.3,11,56,8,20,105.970938,-1.670938,2.792032
3,87.6,11,31,8,47,89.327100,-1.727100,2.982875
4,95.9,7,52,6,33,95.649244,0.250756,0.062878
5,109.2,11,55,9,22,105.274557,3.925443,15.409100
6,102.7,3,71,17,6,104.148669,-1.448669,2.098642
7,72.5,1,31,22,44,75.674989,-3.174989,10.080552
8,93.1,2,54,18,22,91.721651,1.378349,1.899847
9,115.9,21,47,4,26,115.618452,0.281548,0.079269
