In [2]:
# Import libraries
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Create a dataset

value_y_list = [78.5, 74.3, 104.3, 87.6, 95.9, 109.2, 102.7, 72.5, 93.1, 115.9, 83.8, 113.3, 109.4] # valores de Y
value_x1_list = [7, 1, 11, 11, 7, 11, 3, 1, 2, 21, 1, 11, 10] # valores de X1
value_x2_list = [26, 29, 56, 31, 52, 55, 71, 31, 54, 47, 40, 66, 68] # valores de X2
value_x3_list = [6, 15, 8, 8, 6, 9, 17, 22, 18, 4, 23, 9, 8] # valores de X3
value_x4_list = [60, 52, 20, 47, 33, 22, 6, 44, 22, 26, 34, 12, 12] # valores de X4

data_dict = {"Y":value_y_list,
             "X1":value_x1_list,
             "X2":value_x2_list,
             "X3":value_x3_list,
             "X4":value_x4_list}

print(data_dict)

# Turn a dictionary into a dataframe
df = pd.DataFrame(data_dict)

#print(df) Tabla básica
df

{'Y': [78.5, 74.3, 104.3, 87.6, 95.9, 109.2, 102.7, 72.5, 93.1, 115.9, 83.8, 113.3, 109.4], 'X1': [7, 1, 11, 11, 7, 11, 3, 1, 2, 21, 1, 11, 10], 'X2': [26, 29, 56, 31, 52, 55, 71, 31, 54, 47, 40, 66, 68], 'X3': [6, 15, 8, 8, 6, 9, 17, 22, 18, 4, 23, 9, 8], 'X4': [60, 52, 20, 47, 33, 22, 6, 44, 22, 26, 34, 12, 12]}


,Y,X1,X2,X3,X4
0,78.5,7,26,6,60
1,74.3,1,29,15,52
2,104.3,11,56,8,20
3,87.6,11,31,8,47
4,95.9,7,52,6,33
5,109.2,11,55,9,22
6,102.7,3,71,17,6
7,72.5,1,31,22,44
8,93.1,2,54,18,22
9,115.9,21,47,4,26


In [3]:
import numpy as np

# Convert the DataFrame to a NumPy array
matrix = df.values

# Replace the first column with ones
matrix[:, 0] = 1

# Display the modified matrix
print(matrix)

[[ 1.  7. 26.  6. 60.]
 [ 1.  1. 29. 15. 52.]
 [ 1. 11. 56.  8. 20.]
 [ 1. 11. 31.  8. 47.]
 [ 1.  7. 52.  6. 33.]
 [ 1. 11. 55.  9. 22.]
 [ 1.  3. 71. 17.  6.]
 [ 1.  1. 31. 22. 44.]
 [ 1.  2. 54. 18. 22.]
 [ 1. 21. 47.  4. 26.]
 [ 1.  1. 40. 23. 34.]
 [ 1. 11. 66.  9. 12.]
 [ 1. 10. 68.  8. 12.]]
